### ISSUE TITLE
VS2017 not create link

### ISSUE THREAD

**Issue by amatteo78sitav** [golavr/ConfigurationTransform#10]
Hello,

I follow your guide, but when I try click on app.config for copy link to app.debug.config, I have message "not change were made" ??
Thanks

M.

**Comment by golavr** [comment]
@amatteo78  not sure i understand your problem

**Comment by tdmiller** [comment]
I am having a similar issue with VS2019. I add a linked app.config file, but when I add config transforms, no transform files are created and the dialog appears as if the operation is successful; then, when attempting a second time, it gives me the same message as the OP above--no changes were made. 

That said, I have no issues with adding transforms to concrete app.config file instances in VS2019, only with linked app.config files.

**Comment by SteveSiggs** [comment]
Same problem here with VS2017: I right-click app.config to "add config transforms" but no transform files are created. The dialog appears as if the operation is successful; then, when attempting a second time, it gives me the same message "no changes were made".

Why are the app.debug.config and app.release.config files not being created...?

**Comment by SteveSiggs** [comment]
Got there in the end... highlight any file in the project and click "Show All Files". Easy when you know how!

![image](https://user-images.githubusercontent.com/56023900/65978249-47dfe580-e46b-11e9-9d00-0565e503d56f.png)
