### ISSUE TITLE
Only show "Add Transform" and "Show Transform" where if makes sense

### ISSUE THREAD

**Issue by enkelmedia** [golavr/ConfigurationTransform#13]
Would be good to include some logic to ConfigurationTransformPackage.cs -> BeforeQueryStatus()-methods to only show each options when it makes sense.

What I'm thinking:

**Add Configuration Transforms**
Should only be visible (or maybe enabled) when the selected file is a .config-file that has no children.

**Preview Configuration Transforms**
Should only be visible (or maybe enabled) when the selected file has a parent file that is a .config-file. This means that the selected file is an actual transform.

**Comment by golavr** [comment]
Add Configuration Transforms
Should only be visible (or maybe enabled) when the selected file is a .config-file that has no children.
**if i'll take this approach user won't be able to add new configs after adding new build configurations(e.g. Debug/Release/Integration)**

**Comment by enkelmedia** [comment]
True! 

Good point, maybe the second idea with only showing the transform-option when the config file has a parent that is a config file could work?

**Comment by golavr** [comment]
go ahead and do the change for preview
