### ISSUE TITLE
Line breaks not maintained

### ISSUE THREAD

**Issue by resc-git** [golavr/ConfigurationTransform#18]
Line breaks between attributes (+elements) are removed. This causes the preview to not show the changes in a meaningful manner.

If the given config is:
```
<Setting1
    value1="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    value2="b"
    value3="3"
/>
```

And the transform is:
```
<Setting1 xdt:Transform="SetAttributes(value2)"
    value2="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
/>
```

The result is:
`<Setting1 value1="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" value2="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" value3="3"/>`

Depending of the number of attributes or the length of the values, the line does not fit on the visible part of the screen what makes it difficult to see the changes.

I would like to have it like:
```
<Setting1
    value1="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    value2="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    value3="3"
/>
```
what causes the preview to mark only the lines (value1, value2) as modified.

**Comment by golavr** [comment]
Unfortunately i cannot control this behavior.
