### ISSUE TITLE
Configuration changes not output if app.XXX.config is not present

### ISSUE THREAD

**Issue by NightOwl888** [golavr/ConfigurationTransform#22]
I just spent quite a bit of time trying to work out why a new configuration setting wasn't being read when debugging for a ClickOnce project.

It turns out that it was all due to the fact that I never created an `app.Debug.config` file when upgrading the project, thus the entire config transform process was skipped.

```xml
  <Target Name="app_config_AfterCompile" AfterTargets="AfterCompile" Condition="Exists('app.$(Configuration).config')">
	<!--Generate transformed app config in the intermediate directory-->
	<TransformXml Source="app.config" Destination="$(IntermediateOutputPath)$(TargetFileName).config" Transform="app.$(Configuration).config" />
	<!--Force build process to use the transformed configuration file from now on.-->
	<ItemGroup>
	  <AppConfigWithTargetPath Remove="@(AppConfigWithTargetPath)" />
	  <AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config">
		<TargetPath>$(TargetFileName).config</TargetPath>
	  </AppConfigWithTargetPath>
	</ItemGroup>
  </Target>
```

Essentially the `Condition="Exists('app.$(Configuration).config')"` is skipping the whole transform process. I suppose it was logical to assume that if you skipped it, the default MSBuild behavior of copying the `App.config` file over to `MyApp.exe.config` would take place, but that is not what is happening. Although `MyApp.exe.config` does get generated, it is apparently not being done based on the latest version of `App.config`.

Just to be clear, I don't need to do any transformation during debugging. But without an `app.Debug.config` file, debugging is working but the build does not pass through the latest changes to the config settings. Adding the config file solves the issue, but it would definitely be best if the MSBuild configuration didn't require one in order to output the right `.config` settings.

**Comment by golavr** [comment]
@NightOwl888 thanks for bringing up this behavior, i see you point
