### ISSUE TITLE
Last version 3.5.0 has a dependency on Microsoft.VisualStudio.Shell.15.0

### ISSUE THREAD

**Issue by Shabrych** [golavr/ConfigurationTransform#23]
it kills VS2015

**Comment by Applesauce314** [comment]
Same problem here, downloading the 3.3 version in the meantime did fix the issue, but I had to be sure jump in to extensions and updates and disable auto update.

**Comment by golavr** [comment]
thanks for pointing that out

**Comment by golavr** [comment]
please check v3.5.1

**Comment by Applesauce314** [comment]
Adding configs is working, but _Preview Config Transforms_ fails with "_Cannot find source config_",
Thanks for the quick response.
my transforms are pretty simple so this not working is not a huge deal for me.

**Comment by golavr** [comment]
please make sure you right click preview on the transformed config `app.{env}.config` and not the source `app.config`

**Comment by Applesauce314** [comment]
> please make sure you right click preview on the transformed config app.{env}.config and not the source app.config

Woops. looks like everything is fine.
