### ISSUE TITLE
Xml Node inserted twice on tripple solution configuration

### ISSUE THREAD

**Issue by TheNetStriker** [golavr/ConfigurationTransform#26]
I've configured a third solution configuration for a test installation of my software. So I also added a third config transformation file to set the specific config values for my test installation. The problem is that the extension seems to execute an insert transformation twice. Here is how I've configured my project:

Those are the names of my config transform files:
app.Debug.config
app.Release.config
app.Test.config

The app.Release.config and app.Test.config both contain this transformation:
```
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <system.serviceModel>
    <bindings>
      <customBinding>
        <binding name="MyBinding" xdt:Locator="Match(name)">
          <httpTransport xdt:Transform="Remove" />
          <httpsTransport xdt:Transform="Insert" />
        </binding>
      </customBinding>
    </bindings>
  </system.serviceModel>
</configuration>
```

As a result I'm getting the httpsTransport element twice when compiling in "Release" or "Test" solution configuration. As a workarround I've now simply added <httpsTransport xdt:Transform="Remove" /> bevor adding the httpsTransport again.

Is there a better solution to this problem or is this maybe a bug in the extension?

**Comment by golavr** [comment]
@TheNetStriker to have a better understanding of the problem i need to see the source config (app.config)

**Comment by TheNetStriker** [comment]
The part in the config looks like this:

```
<configuration>
  <system.serviceModel>
    <bindings>
      <customBinding>
        <binding name="MyBinding" closeTimeout="00:01:00"
          openTimeout="00:01:00" receiveTimeout="00:10:00" sendTimeout="00:10:00">
          <textMessageEncoding messageVersion="Soap12" writeEncoding="utf-8">
            <readerQuotas maxDepth="100" maxStringContentLength="2147483647"
              maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxNameTableCharCount="2147483647" />
          </textMessageEncoding>
          <httpTransport maxBufferPoolSize="2147483647" maxReceivedMessageSize="2147483647" allowCookies="false"
                         authenticationScheme="Negotiate" bypassProxyOnLocal="false" hostNameComparisonMode="StrongWildcard"
                         maxBufferSize="2147483647" transferMode="Buffered" useDefaultWebProxy="true" />
        </binding>
      </customBinding>
    </bindings>
  </system.serviceModel>
</configuration>
```

With the transformation I'm trying to remove the httpTransport node and add the httpsTransport node. But when I have a "Release" and a "Test" transformation file, the httpsTransport node is added twice for some reason.

**Comment by golavr** [comment]
i checked the configs you sent with .net 4 console app
on my end it's not added twice
BTW i also checked the actual file in bin folder not just the preview

![image](https://user-images.githubusercontent.com/22896741/66874419-bb2d3f80-efb3-11e9-8d12-a316e45ee095.png)

try to use `xdt:Transform="InsertIfMissing"` and see if that solve your problem

if not please send transformation portion in csproj file and which project type and framework you are using
``` 
<UsingTask TaskName ...
 ...</Target>
```
