### ISSUE TITLE
Unable to create transform file(s)

### ISSUE THREAD

**Issue by codewithtyler** [golavr/ConfigurationTransform#3]
When I right click on my Web.config file and click on "Add Config Transforms" I get the following error:

![image](https://user-images.githubusercontent.com/2483249/36694914-5515d2c2-1b05-11e8-9315-8ff412993d50.png)

**Comment by golavr** [comment]
Assuming you are building Web Application
Config transformation is natively supported in VS so you don't need to use any extension tool to do it
[https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/web-config-transformations](url)
