### ISSUE TITLE
error  : The attribute "xmlns" in element <UsingTask> is unrecognized.

### ISSUE THREAD

**Issue by vrejohanian** [golavr/ConfigurationTransform#35]
After "Add Config Transform" the project unloaded and throws this error (VS2019):
C:\*\<solutionFolder>\<projectName>.csproj : error  : The attribute "xmlns" in element <UsingTask> is unrecognized.  C:\*\<solutionFolder>\<projectName>.csproj

the following lines is added to the project (which the xmlns that causing the problem):
(at the top) : <?xml version="1.0" encoding="utf-8"?>

(in the <project> at the end): 
  <UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />
  <Target Name="web_config_AfterBuild" AfterTargets="AfterBuild" Condition="Exists('web.$(Configuration).config')" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <TransformXml Source="web.config" Destination="$(OutputPath)web.config" Transform="web.$(Configuration).config" />
  </Target>

any idea why?

**Comment by tralots** [comment]
As far as I`m aware it will throw this error if you`re using .net core instead of .net framework. I tried both just now and .net core projects do throw this exception. Does work with .net framework thou.

**Comment by vrejohanian** [comment]
I see, thanks. From: tralotsSent: April 7, 2021 12:44To: golavr/ConfigurationTransformCc: Vrej Ohanian; AuthorSubject: Re: [golavr/ConfigurationTransform] error : The attribute "xmlns" in element <UsingTask> is unrecognized. (#35) As long as Im aware it will throw this error if youre using .net core instead of .net framework. I tried both just now and .net core projects do throw this exception. Does work with .net framework thou.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by spanishkangaroo** [comment]
It's failing for me with .NET 5.0 as target platform.
