### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by 6rill2000** [golavr/ConfigurationTransform#36]
Please, make this extension compatible with the new Visual Studio 2022

**Comment by utech626** [comment]
I'm working on it as time permits

**Comment by xevimayo** [comment]
Please this is really needed in Visual Studio 2022!!

**Comment by golavr** [comment]
Why aren't you using the appsettings.json? When it was released, I stopped maintaining this repo. I personally use it, it's way better.

**Comment by utech626** [comment]
Microsoft has released SlowCheetah for Visual Studio 2022. Same functionality

**Comment by golavr** [comment]
@utech626 @xevimayo @6rill2000 I advise you to read [Configuration in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration) carefully before taking any action. I developed this extension as Microsoft didn't addressed the configuration issue, once they released configuration providers I didn't see any sense to maintain my extension. I'm using it in many production projects, the way it works is very powerful and play very well w/ DI. The same thing applies for SlowCheetah, not sure why they keep it while having better way to handle configuration.
