### ISSUE TITLE
DependentUpon makes app.env.config files invisible in VB project

### ISSUE THREAD

**Issue by NightOwl888** [golavr/ConfigurationTransform#9]
Apparently, the nesting feature of files has been removed from VB projects. When you add a `<DependentUpon/>` element, the file is not shown in Visual Studio (2015 Community in my case).

See the following for more info: https://developercommunity.visualstudio.com/content/problem/165081/vb-project-not-showing-dependentupon-files-anymore.html

I tried "Show All Files" as the post suggests, but that also does not show the `app.env.config` files in Visual Studio. So, I would suggest removing the `<DependentUpon>` elements when the project is VB, as this "feature" doesn't seem to work at all in that environment.

The transforms seem to go smoothly, though. Nice work!

**Comment by golavr** [comment]
thanks @NightOwl888 
i was not planning to support VB but it seems very easy fix so it might get in in the next version.

**Comment by NightOwl888** [comment]
Actually, I tried another project and it seems that the "Show All Files" option does show them (and nested). So, this is probably not something that should be fixed here in that sense. 

Perhaps there could be a message spit out somewhere (the app.config file maybe) that points out that "Show All Files" is required in order to see the environment specific config files in VB. Or perhaps put in an option to not use `DependentUpon`.

Or if you would rather leave it the way it is, that is probably fine for "normal" VB users, but those of us who have gotten accustomed to C# aren't used to having to "Show All Files" to do normal config work.
